columns:
  - Date: object 
  - Location: object 
  - MinTemp: float64
  - MaxTemp: float64
  - Rainfall: float64
  - Evaporation: float64
  - Sunshine: float64
  - WindGustDir: object 
  - WindGustSpeed: float64
  - WindDir9am: object 
  - WindDir3pm: object 
  - WindSpeed9am: float64
  - WindSpeed3pm: float64
  - Humidity9am: float64
  - Humidity3pm: float64
  - Pressure9am: float64
  - Pressure3pm: float64
  - Cloud9am: float64
  - Cloud3pm: float64
  - Temp9am: float64
  - Temp3pm: float64
  - RainToday: object 
  - RainTomorrow: object

numerical_columns:
  - MinTemp
  - MaxTemp
  - Rainfall
  - Evaporation
  - Sunshine
  - WindGustSpeed
  - WindSpeed9am
  - WindSpeed3pm
  - Humidity9am
  - Humidity3pm
  - Pressure9am
  - Pressure3pm
  - Cloud9am
  - Cloud3pm
  - Temp9am
  - Temp3pm

categorical_columns:
  - Date
  - Location
  - WindGustDir
  - WindDir9am
  - WindDir3pm
  - RainToday
  - RainTomorrow

drop_columns:
  - Date
  - MinTemp
  - MaxTemp
  - Evaporation
  - Sunshine
  - Pressure9am
  - Pressure3pm
  - Cloud9am
  - Cloud3pm
  - Temp9am
  - Temp3pm

# for data transformation
num_columns:
  - Rainfall
  - WindGustSpeed
  - WindSpeed9am
  - WindSpeed3pm
  - Humidity9am
  - Humidity3pm
  - WindGustAngle
  - WindAngle9am
  - WindAngle3pm

one_hot_columns:
  - Location
  - RainToday

ordinal_column:
  - RainTomorrow

tranform_columns:
  - WindGustDir
  - WindDir9am
  - WindDir3pm